// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrafficBrainAPI.Data;

#nullable disable

namespace TrafficBrainAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrafficBrainAPI.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasColumnType("text");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DistrictId = 1,
                            IsActive = true,
                            Name = "Lilongwe"
                        },
                        new
                        {
                            Id = 2,
                            DistrictId = 2,
                            IsActive = true,
                            Name = "Blantyre"
                        },
                        new
                        {
                            Id = 3,
                            DistrictId = 3,
                            IsActive = true,
                            Name = "Mzuzu"
                        },
                        new
                        {
                            Id = 4,
                            DistrictId = 4,
                            IsActive = true,
                            Name = "Zomba"
                        });
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Lilongwe",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Blantyre",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Mzimba",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Zomba",
                            RegionId = 3
                        });
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.EmergencyEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CorridorCleared")
                        .HasColumnType("boolean");

                    b.Property<string>("CorridorJunctions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TimeSavedMinutes")
                        .HasColumnType("double precision");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("EmergencyEvents");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResolvedBy")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.HasIndex("ReportedById");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Junction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastDataReceived")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoadNames")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Junctions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 1,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -13.9626,
                            Longitude = 33.774099999999997,
                            Name = "Kamuzu Procession Rd Junction",
                            RoadNames = "Kamuzu Procession Rd / Kenyatta Rd"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 1,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -13.9689,
                            Longitude = 33.787799999999997,
                            Name = "Glyn Jones Rd Junction",
                            RoadNames = "Glyn Jones Rd / Paul Kagame Rd"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 1,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -13.974500000000001,
                            Longitude = 33.781199999999998,
                            Name = "Area 18 Junction",
                            RoadNames = "Presidential Way / Area 18 Rd"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 2,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -15.786099999999999,
                            Longitude = 35.005800000000001,
                            Name = "Chipembere Highway Junction",
                            RoadNames = "Chipembere Highway / Victoria Ave"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 2,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -15.7925,
                            Longitude = 35.002099999999999,
                            Name = "Kamuzu Highway Junction",
                            RoadNames = "Kamuzu Highway / Kidney Crescent"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 3,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -11.4657,
                            Longitude = 34.0199,
                            Name = "Mzuzu City Centre Junction",
                            RoadNames = "M1 Road / Orton Chirwa Ave"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            ControlMode = "Auto",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DistrictId = 4,
                            IsActive = true,
                            IsOnline = false,
                            Latitude = -15.3833,
                            Longitude = 35.316699999999997,
                            Name = "Zomba Main Junction",
                            RoadNames = "M3 Road / College Rd"
                        });
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.JunctionOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomGreenDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForcedDirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.HasIndex("OfficerId");

                    b.ToTable("JunctionOverrides");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Lane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<int>("LaneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("Lanes");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.PerformanceMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageWaitTime")
                        .HasColumnType("double precision");

                    b.Property<double>("CO2SavedKg")
                        .HasColumnType("double precision");

                    b.Property<int>("CongestionScore")
                        .HasColumnType("integer");

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("FuelWasteEstimateLitres")
                        .HasColumnType("double precision");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<double>("MaxWaitTime")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ThroughputPerHour")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalVehiclesProcessed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("PerformanceMetrics");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Northern"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Central"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Southern"
                        });
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.ShiftRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HandoverNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ShiftEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ShiftStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalIncidentsHandled")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOverrides")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.HasIndex("OfficerId");

                    b.ToTable("ShiftRecords");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.SignalPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GreenDuration")
                        .HasColumnType("integer");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<int>("PhaseNumber")
                        .HasColumnType("integer");

                    b.Property<int>("QueueLengthAtChange")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RedDuration")
                        .HasColumnType("integer");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WaitTimeAfter")
                        .HasColumnType("double precision");

                    b.Property<double>("WaitTimeBefore")
                        .HasColumnType("double precision");

                    b.Property<int>("YellowDuration")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("SignalPhases");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.SmsAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderMessageId")
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SmsAlerts");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.TrafficPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<int>("CongestionScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpectedVehicleCount")
                        .HasColumnType("integer");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PredictedFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PredictionBasis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("TrafficPredictions");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BadgeNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeNumber = "TB-ADMIN-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            District = "Lilongwe",
                            Email = "admin@trafficbrain.mw",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$IHlZ4GMAExqpiNlIKAj2HukmMj.fuvtjXHYFjcjz9ZwHWfS1i/aaq",
                            PhoneNumber = "+265999000001",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.VehicleCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("Buses")
                        .HasColumnType("integer");

                    b.Property<int>("Cars")
                        .HasColumnType("integer");

                    b.Property<int>("CongestionScore")
                        .HasColumnType("integer");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<string>("Lane")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("LaneId")
                        .HasColumnType("integer");

                    b.Property<int>("Motorcycles")
                        .HasColumnType("integer");

                    b.Property<int>("Pedestrians")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalVehicles")
                        .HasColumnType("integer");

                    b.Property<int>("Trucks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.HasIndex("LaneId");

                    b.ToTable("VehicleCounts");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.ViolationEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JunctionId")
                        .HasColumnType("integer");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JunctionId");

                    b.ToTable("ViolationEvents");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.WeatherCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DistrictId")
                        .HasColumnType("integer");

                    b.Property<double>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<double>("Visibility")
                        .HasColumnType("double precision");

                    b.Property<string>("WeatherImpact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("WindSpeed")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("WeatherConditions");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Alert", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("Alerts")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.City", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.District", "District")
                        .WithMany("Cities")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.District", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Region", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.EmergencyEvent", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("EmergencyEvents")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Incident", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("Incidents")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficBrainAPI.Models.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Junction");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Junction", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.City", "City")
                        .WithMany("Junctions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficBrainAPI.Models.District", "District")
                        .WithMany("Junctions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.JunctionOverride", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("Overrides")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficBrainAPI.Models.User", "Officer")
                        .WithMany("Overrides")
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Junction");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Lane", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("Lanes")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.PerformanceMetric", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("PerformanceMetrics")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.ShiftRecord", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany()
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficBrainAPI.Models.User", "Officer")
                        .WithMany()
                        .HasForeignKey("OfficerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Junction");

                    b.Navigation("Officer");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.SignalPhase", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("SignalPhases")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.SystemLog", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.TrafficPrediction", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("Predictions")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.VehicleCount", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany("VehicleCounts")
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrafficBrainAPI.Models.Lane", "LaneRef")
                        .WithMany()
                        .HasForeignKey("LaneId");

                    b.Navigation("Junction");

                    b.Navigation("LaneRef");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.ViolationEvent", b =>
                {
                    b.HasOne("TrafficBrainAPI.Models.Junction", "Junction")
                        .WithMany()
                        .HasForeignKey("JunctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Junction");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.City", b =>
                {
                    b.Navigation("Junctions");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.District", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Junctions");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Junction", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("EmergencyEvents");

                    b.Navigation("Incidents");

                    b.Navigation("Lanes");

                    b.Navigation("Overrides");

                    b.Navigation("PerformanceMetrics");

                    b.Navigation("Predictions");

                    b.Navigation("SignalPhases");

                    b.Navigation("VehicleCounts");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.Region", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("TrafficBrainAPI.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Overrides");
                });
#pragma warning restore 612, 618
        }
    }
}
